// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ce79b683-7fb3-449b-9a28-63812737c671";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMotorStartChange();
void onMotorStopChange();

CloudRelativeHumidity main_Tank;
CloudRelativeHumidity side_Tank;
bool motor;
bool motor_Start;
bool motor_Stop;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(main_Tank, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(side_Tank, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor_Start, READWRITE, ON_CHANGE, onMotorStartChange);
  ArduinoCloud.addProperty(motor_Stop, READWRITE, ON_CHANGE, onMotorStopChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
